name: windows

on:
  push:

jobs:
  containers:
      name: win-latest
      runs-on: windows-latest
      container:
        image: windows/insider:latest
      steps:
      - run: [System.Environment]::OSVersion.Version
        shell: powershell

